routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'weatherController');
Route::resource('orders', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    // Перебираем продукты из заказа, что бы сосчитать сумму заказа
    public function orderPrice()
    {
        $totalPrice = 0;
        foreach ($this->orderProducts as $product) {
            $totalPrice+= $product->price * $product->quantity;
        }
        return $totalPrice;
    }
    // Преобразуем id статуса заказа в текст
    public function status()
    {
        $status = [0 => 'новый', 10 => 'подтвержден', 20 => 'завершен'];
        return $status[$this->status];
    }
    // Методы для определения отношений между моделями
    public function orderProducts()
    {
        return $this->hasMany(OrderProduct::class);
    }
    public function products()
    {
        return $this->belongsToMany(Product::class, 'order_products');
    }
    public function partner()
    {
        return $this->hasOne(Partner::class, 'id', 'partner_id');
    }
}

app/OrderProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderProduct extends Model
{
    // Методы для определения отношений между моделями
    public function product()
    {
        return $this->hasOne(Product::class, 'id', 'product_id');
    }
}

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Выводим все заказы
        $Orders = \App\Order::orderBy('id', 'desc')->limit(20)->get();
        return view('orders.index', ['Orders' => $Orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Order = \App\Order::find($id);
        return view('orders.update', ['Order' => $Order, 'Partners' => \App\Partner::orderBy('name')->get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Проверяем указан ли email, и формат email
        $request->validate([
            'client_email' => 'required|email',
        ]);
        // Берём модель
        $Order = \App\Order::find($id);
        // Обновляем параметры
        $Order->client_email = $request->client_email;
        $Order->partner_id   = $request->partner_id;
        $Order->status       = $request->status;
        // Сохраняем
        $Order->save();
        // Возвращаемся на страницу заказа
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/weatherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class weatherController extends Controller
{
    function __invoke()
    {
        $temp = '';
        // Получаем данные от яндекса
        $client = new \GuzzleHttp\Client(['headers' => ['X-Yandex-API-Key' =>'b93f828d-046d-4c6b-87f5-5710425aa4e0']]);
        $res = $client->request('GET', 'https://api.weather.yandex.ru/v1/informers?lon=34.374304&lat=53.279268');
        if ($res->getStatusCode() == 200)
            $temp = json_decode($res->getBody())->fact->temp;
        // Если температура выше 0 - добавляем знак "+"
        if (intval($temp) > 0)
            $temp = '+'.$temp;
        // Выводим результат
        return view('weather', ['temp' => $temp]);
    }
}

resources/views/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="/js/app.js"></script>

        <link rel="stylesheet" type="text/css" href="/css/app.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">

        <title>Тестовое задание</title>

    </head>
    <body>
        <div class="flex-center position-ref">
            <div class="content">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @yield('content')
            </div>
        </div>
    </body>
</html>

resources/views/orders/index.blade.php
@extends('app')
@section('content')
    <h1>Список заказов</h1>

    <div class="content">
        <table class="table">
            <tr>
                <th>ид заказа</th>
                <th>название партнера</th>
                <th>стоимость заказа</th>
                <th>наименование состав заказа</th>
                <th>статус заказа</th>
            </tr>
        @foreach($Orders as $order)
            <tr>
                <td><a href="{{ route('orders.edit', $order->id) }}">{{ $order->id }}</td>
                <td>{{ $order->partner->name }}</td>
                <td>{{ $order->orderPrice() }}</td>
                <td>
                    <ul>
                        @foreach($order->products as $product)
                            <li>{{ $product->name }}</li>
                        @endforeach
                    </ul>
                </td>
                <td>{{ $order->status() }}</td>
            </tr>
        @endforeach
        </table>
    </div>
@stop

resources/views/orders/update.blade.php
@extends('app')
@section('content')
    <h1>Заказ №{{ $Order->id }}</h1>
    <div class="content">
        {{ Form::open(['route' => ['orders.update', $Order->id]]) }}
            <input type="hidden" name="_method" value="put" />
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="client_email" value="{{ $Order->client_email }}" id="email">
            </div>
            <div class="form-group">
                <label for="partner">Партнёр</label>
                <select class="form-control" name="partner_id" id="partner">
                    @foreach($Partners as $partner)
                        <option @if($partner->id == $Order->partner_id) selected @endif value="{{ $partner->id }}">{{ $partner->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Продукты</label>
                <ul>
                    @foreach($Order->orderProducts as $orderProduct)
                        <li><span class="col-md-6">{{ $orderProduct->product->name }}</span><span>{{ $orderProduct->quantity }} шт.</span></li>
                    @endforeach
                </ul>
            </div>
            <div class="form-group">
                <label for="status">Статус</label>
                <select class="form-control" name="status" id="status">
                    <option value="0">новый</option>
                    <option value="10" @if($Order->status == 10) selected @endif >подтвержден</option>
                    <option value="20" @if($Order->status == 10) selected @endif >завершен</option>
                </select>
            </div>
            <div class="form-group">
                <label>Стоимость заказа</label>
                {{ $Order->orderPrice() }}
            </div>


            <input type="submit" class="btn btn-primary" value="Обновить">
        {{ Form::close() }}
    </div>
@stop

resources/views/weather.blade.php
@extends('app')
@section('content')
    <div class="title m-b-md">
        Погода в Брянске
    </div>

    <div class="links">
        {{ $temp }}°C
    </div>
@stop